### ISSUE TITLE
Detect duplicate song entries

### ISSUE THREAD

**Issue by ANewDawn** [the-expanse/SideQuest#120]
When creating packs with a lot of songs sometimes it's hard to remember which songs are in it. If you add a song already in the pack it shows up as two duplicate songs in beat saber.

Be nice if side quest could detect two entries the same.

**Comment by shaneharris** [comment]
the ability to reuse the same song is actually a feature! i dont think it makes sense to add a constraint there, people may want to reuse the same song in the same pack and ill get it in the ear if i add a constraint to prevent it.

**Comment by ANewDawn** [comment]
Maybe showing a dialog box informing the user there is a duplicate and ask if they wish to keep it, would help both set of users.

It's not really a matter of not allowing duplicates more a case of knowing there are duplicates. Even a message on the bottom information bar would suffice.

**Comment by shaneharris** [comment]
this is a good idea in that case! leave this with me I will look at how best this could be implemented! 

Thanks!

**Comment by BrainSlugs83** [comment]
On a side note, I've found the app to be very buggy when it comes to managing songs (which is why I end up with duplicate entries).  E.g.  If you hit delete in a song and then refresh, sometimes it comes right back, etc.  I find that I have to go through multiple delete / refresh cycles.  And sometimes it gets confused and deletes (and /or ignores) the art too. It's really painful to use in this state.

**Comment by shaneharris** [comment]
we have a new version coming very soon that is a complete rewrite of the song/pack manager - hopefully it is much more stable now.
