### ISSUE TITLE
Suggestion: easier mapping with quest beat saber

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#157]
I have been mapping songs, but at one point lost progress because I tried playtesting and sidequest turned the .json files to .dat files (I'm using mediocremapper) 

It would be great if sidequest would notgo directly into the WIP songs folder but instead if it encounters such a folder that it will copy the contents to some kind of "playtest" folder/level pack so songs are easier to find while working on them and your original files don't get messed up

**Comment by ryanlauderbach** [comment]
You could make a copy of your song folder so you can still edit the song after the copy gets converted.

**Comment by RedBrumbler** [comment]
yeah I could do that, but this way of doing things would make it a hell of a lot more convenient

**Comment by shaneharris** [comment]
@RedBrumbler its very hard for SideQuest to know what is and isn't a working folder. It runs songe-converter automatically over the folders and that replaces the json files with .dat files. The bsaber folder is the playlist folder as far as SideQuest is concerned. There is no folder for packs as they are just an index listing in the `__json.json` file. 

I think this workflow it a bit out of the scope of what SideQuest should do, I think holding your songs in an intermediary working folder before moving them into SideQuest makes the most sense, since you are already moving files around. 

Please let me know if i have misunderstood the requirement here.
