### ISSUE TITLE
Suggestion: Method of selecting from multiple attached devices

### ISSUE THREAD

**Issue by cmdrflexo** [the-expanse/SideQuest#19]
Right now the whole application locks you out if you have more then one device attached to the computer. 
Cases where you might see the user with two or more devices are somewhat rare, but not far outside of being a constant annoyance for certain users.

The suggestion is to put a drop-down or similar selection method into the application to allow the user to target an attached device. The device names can be pulled from the connection as well so you do not need to show a bunch of cryptic device IDs

**Comment by jcuadrad** [comment]
This would be amazingly helpful for many! I am currently looking for a solution to deploy to multiple headsets as easily as possible and SideQuest is this feature away from being the perfect solution!

Since we don't have access to Release Channels on the Quest, many enterprise solutions might find this very helpful.

**Comment by shaneharris** [comment]
SideQuest is really intended as a consumer facing application so i don't think this is really on the road map for this version of sidequest. We can look at a enterprise version down the line if no one else has done it by then. 

Thanks!
