### ISSUE TITLE
suggestion: allow windows to automatically open sidequest when it detects a quest is connected

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#227]
I discovered I can set preferences on what to do when I connect devices to my windows machine, and was wondering if it was possible to use sidequest as the standard option when my pc detects my quest, this is more a QOL request so there's no rush (if it's possible at all) I just think it would be a cool addition!

![afbeelding](https://user-images.githubusercontent.com/51795403/60550144-4c3f1a00-9d27-11e9-99d1-ac5cca352d96.png)

**Comment by SpookyBear0** [comment]
I don't think this would be possible except for opening when it detects any android device, there is no way to detect if it is an oculus quest. I will try to get working on this soon.

**Comment by RedBrumbler** [comment]
Windows clearly recognizes the quest as a quest, so that part should be possible

**Comment by SpookyBear0** [comment]
Maybe setting the model number (the one when you run: adb devices) and when it detects that quest with that model number than it would open. (what you are talking about wouldn't be possible as far as I know, because apps can't see that the same way windows does, and it wouldn't work cross-platform.)

**Comment by shaneharris** [comment]
closing as not easily possible across platform
