### ISSUE TITLE
Add websocket to allow for remote installs

### ISSUE THREAD

**Issue by Neeeser** [the-expanse/SideQuest#259]
It would be nice to have a web interface with sidequest that could be installed as a daemon. A web interface would allow for apk's to be installed directly from the quest with no computer needed until the quest is rebooted due to abd driver limits.

**Comment by shaneharris** [comment]
I think this is a good idea, but rather than a web interface I think i would do a relay through a websocket  - this means remote could be anywhere in the world and doesn't involve any of the ip address stuff. I plan on making the sidequest website be able to remote control the sidequest app from anywhere if you are logged into both. That will provide the most value at the most convenience.

**Comment by Neeeser** [comment]
Oh ya that is a great idea! Glad to hear your working on this love the work!

**Comment by shaneharris** [comment]
this is finally coming in the latest version in a few days
