### ISSUE TITLE
Hide the NSFW section by default

### ISSUE THREAD

**Issue by VivaNOLA** [the-expanse/SideQuest#263]
We're not anti-smut, by any means. People should absolutely be able to access this if they want to. Easily. With just one hand. But, we would love to use this app for providing external beta testers the ability to test our Quest app, but it's 2019 and we simply cannot ask them to install something with NSFW in their face as a default. Wish we lived in a different world, but we don't. We would really appreciate it if this option were down a level in a settings menu or something.

**Comment by ATechAdventurer** [comment]
Thanks for your input, no promises but I will look into it.

**Comment by shaneharris** [comment]
Hi There!

I appreciate your concerns and i completely understand your point of view. I guess my stand point is that I want to help the VR industry over all and I recognise that these developers have made great strides in pushing the technology stack forward. I feel bad that they should be punished and not receive the same opportunity as the rest of us and I think they should be able to have their content accessible too. 

I did add the ability to disable NSFW & Mod content in sidequest ( Settings screen - Destroy the world option at the bottom ) and I have an agreement that the listing for those guys will not contain any graphic content so I would like to keep an open approach like Steam does with these matters. If the content is not offensive, were happy to list it. 

Thanks so much for your thoughts, and lets talk about getting you a fork with these things removed if you would like to distribute it separately. I would be happy to create a branch with the modifications and you can build from there. 

Yours
Shane

**Comment by srvrguy** [comment]
What if we keep the NSFW section but require a one-time click-through when they select the listing on the side? Basically, it would avoid being accidentally exposed to "mature" content if you accidentally hit it, but not a high hurdle if you actually want it.

**Comment by shaneharris** [comment]
not a bad idea! ill see how we go with keeping the listing reasonably safe and if we get a lot of people who have an issue then we can look at it again.

**Comment by doublevr** [comment]
Having an option to opt-out would be a saviour.

**Comment by Jukilum** [comment]
I want the NSFW section gone, preferably entirely, not just as an option, (about 60% of the US agrees it is bad according to the latest poll, so I'm sure I'm not alone in this: https://news.gallup.com/poll/257858/birth-control-tops-list-morally-acceptable-issues.aspx ,) and the Destroy The World button is extremely unclear on what it does. 

It also seems odd to group NSFW and Mods together.

**Comment by srvrguy** [comment]
Trying to appeal to a moral stance seems kinda odd, especially given the international audience involved in both using and developing this tool. (The main developer is from the UK, a few contributors are in mainland Europe, IIRC, and I'm from the US.) Each country has their own cultural standards as to what's appropriate, so it's a difficult balancing act in some cases. Because of that you're probably not going to get the NSFW content removed entirely, sorry.

The more active contributors have had some internal conversations on the whole NSFW thing, and are discussing some ways to make things a bit more acceptable for a wider audience as we do understand that not everyone appreciates "adult" content and that in some cases such as with kids, it's not appropriate to show it.

I think we (the contributors to this application) all agree that the toggle is poorly named, and that will probably be changed eventually once an action is decided on it. It was a quick addition to allow for a "safer" experience until a more complete solution can be developed.

For me personally, I'm in favor of disabling by default where there's just an entry shown, but it's blank until you toggle adult content on. Ultimately, however, I don't have the final say on what will be done. I can only offer my opinion.

As for the mods section disappearing, I think that's because some of the Beat Saber mods have "adult" content in them (we have some harsher swear words and also a phallic saber replacement mod) and there isn't a way to separate those out at this time.

**Comment by Jukilum** [comment]
I know I’m unlikely to get my wish, but I thought I’d register it. With the link I was just trying to show that the number of people who have a problem with such things is large, which is something that doesn’t usually come across in internet discussions. 

Rereading my previous post I think I came across a bit more belligerent than I intended, so I apologize for that.

**Comment by shaneharris** [comment]
The stats I have show that its one of our most popular apps. I havent only had 3 people show real issue with it, including this issue out of 100k downloads. I think those numbers show that people are OK with it. 

I will look at this again in the future, but for now I have a good working relationship with the SLR guys and I am comfortable with our current arrangement that there is an opt out and we have agreed to keep the listing itself free from graphic images. 

I would also like to point out that the option to disable is intentionally cryptic as it is intended to not alert youngsters to its purpose - since my only real concern is kids and age appropriation. 

Im going to close this issue now because i think our stance is clear for now. If you feel so inclined please feel free to open another one.

Thanks so much for all your thoughts and input!
