### ISSUE TITLE
Oculus Touch detected as PS Move (VRigade, Bring it down)

### ISSUE THREAD

**Issue by DarkMorox** [the-expanse/SideQuest#270]
** Sorry if it's not the right place for this issue, I don't know where else to post it. **

Since I've install BeatOn (don't think it's related but I don't remember to have do anything else...), my Oculus Touch are shown as PS Move in games like Vrigade and Bring it Down, and so are not recognized and I can't play those games anymore ... (work wells on Oculus's store apps).
I'vre already played VRigade before, and it played well.

I've already reset the Oculus Quest, reinstall all content and ... still the same issue on those games

Anyone has already have this problem ? How can it be solved ?

**Comment by lifet8kr** [comment]
I hope someone knows how to fix this issue. no SideQuest games are running, I think it was from the Oculus Update.

**Comment by srvrguy** [comment]
It's not because of Beat On. Oculus released an update to the Quest that fixed a lot of issues, but also now more strictly enforces certain application features due to some upcoming support for Oculus Go games. Many of the applications/games available through SideQuest were caught in this change. Most of the developers have made the needed fixes, so you just need to check for and install the latest versions on your headset.

If that doesn't resolve your issue, feel free to reply here and we can investigate further.

**Comment by DarkMorox** [comment]
Redownload Vrigade and works well again. Thanjs srvrguy
