### ISSUE TITLE
Crash/Freeze when browsing in the list of custom songs when playing.

### ISSUE THREAD

**Issue by Vasago** [the-expanse/SideQuest#279]
Steps to reproduce the crash/freeze of beatsaber:
1) Get oculus quest
2) install latest SideQuest (0.6.3)
3) Install latest BeaOn application
4) Download an load something like 100 custom songs (may be less)
5) Listen to their preview a lot.
6) Click on every song and wait for playing its preview sound sometimes move to another song when preview is still playing to start playing another preview opf different song.
7) Repeat and listen to previews only for some time
8) Application freezes whole device.

**Comment by ATechAdventurer** [comment]
What platform are you on? Mac, Windows or Linux?

**Comment by Vasago** [comment]
If you mean which platform I used for installing SideQuest it was Windows 10. Otherwise the Oculus Quest is using Android I guess.

**Comment by shaneharris** [comment]
Hi There! Im afraid this might be better served reported over in the BeatOn Repo since there is nothing in sidequest that can affect this. 

https://github.com/emulamer/BeatOn

TBH what your dealing with is the desktop site loading on the device, the site itself can be very heavy for the device. It might be better to use beatsaver.com instead of bsaber.com, or use the sidequest browser to browser for songs and it will send them to the custom songs list in beat on when you download

**Comment by Vasago** [comment]
Thx reported here: https://github.com/emulamer/BeatOn/issues/72
