### ISSUE TITLE
Sideloaded App with Sidequest but App not showing up under "My Apps". Now i cant uninstall the App.

### ISSUE THREAD

**Issue by ocquesttest** [the-expanse/SideQuest#296]
Hey,

I sideloaded this app with Sidequest, called Octopus Quest Pinball.
https://drive.google.com/uc?id=14_qxsqf6xkkcNG-3LeMCJ7U7iJD-h8UF&export=download

In the Quest it shows up under "Unknown Sources" as Quest Pinball (com.oculus.UnitySample)

But now i want to uninstall the app again.
But it is not showing up in SideQuest under "My Apps" (yes i have checked the "show all" checkbox)
There is just no entry for either Quest Pinball or com.oculus.UnitySample

Seems to be a bug here or something?
Can you please look it up?

**Comment by shaneharris** [comment]
Hi There!
so the apps list in the desktop app is filtered to remove system apps and other apps you dont want to mess with
we do a blanket filter on com.oculus.*
as all the official oculus titles start with com.Oculus.*
but you can turn off the filtering
![i](https://cdn.discordapp.com/attachments/416336256482410506/618068170845978624/unknown.png)

if you don't see the above then grab the latest sidequest at https://xpan.cc/download

**Comment by ocquesttest** [comment]
Yes, i know about the "show all" checkbox. 
As i already wrote, even with this box checked it didnt showed the com.oculus.UnitySample in the "My Apps" list.
Im also on the lastest SideQuest.

Thats why i wrote this issue and even gave you a link for the apk to test it yourself.
There must be some kind of bug.

**Comment by shaneharris** [comment]
Hi @egon my apologies.
i have looked into this further and I now know what the problem is
it is not a bug, but unfortunately the game you are trying to install ( https://xpan.cc/a-36 ) uses the same package name as another app on sidequest, it is therefore detected as that app. There is no way around this and apps should never use the same package name but both that pinball app and the Tuscany VR demo use the same package name as com.oculus.UnitySample - which makes this pinball app come up as Tuscany VR in the My Apps section.


![i](https://cdn.discordapp.com/attachments/416336256482410506/618406821060804628/unknown.png)

I would also like to point out that those apps are not compatible with the Oculus Quest afaik as they were not updated after the latest quest firmware release. This means that the controls unfortunately do not work and this is why I removed them from SideQuest.
