### ISSUE TITLE
Add screencasting feature

### ISSUE THREAD

**Issue by Sp4iK** [the-expanse/SideQuest#297]
This may be interesting to add as a feature both for devs and users. I'm actually using [scrcpy](https://github.com/Genymobile/scrcpy), but it may be a better way with a Chromecast emulator or similar. What do you think?

**Comment by shaneharris** [comment]
I have considered this and there were a few other requests for it too. There are a few issues with using scrcpy in that it requires a java dependency and its only really useful over wireless adb. I'm afraid that is a support nightmare for us as wireless adb is temperamental at best and we already deal with tonnes of support requests due to wifi requirements.

Im not aware of a chromecast emulator ( has to be v3 at least ) and unfortunately even if there was it would be a reverse engineer of a non public api which we also cannot support and is lightly to break.

All nice ideas but in reality we dont have the resources to manage the fall out from such features
