### ISSUE TITLE
Can not use beaton

### ISSUE THREAD

**Issue by bodograumann** [the-expanse/SideQuest#298]
With the latest update of BeatSaber, there is some major problem now. I can’t even tell what exactly is happening. It is quite confusing.

- Got the information, that an update for beatsaber is available. Wouldnt download though. Guess this is because of the patch!?
- Uninstalled and reinstalled beatsaber to get the update. That worked but ofc my scores are gone :-(
- Needed to patch with beaton again, but could not get it to work.
- Looked like it was installed, but when opening beaton in sidequest, it wouldnt load forever and then finally it complained that it cannot access the network address “quest should be on the same network“ (which of course it is)
- Seems at one point when I tried disabling / enabling beaton again in sidequest, it **uninstalled beatsaber**???
- And now I dont even see that beaton button in sidequest anymore, only the beaton icon at the top for installation...
- ofc cant install, because beatsaber was removed. Though not completely it seems, because it still shows in the installed apps in the quest, only to show error message when going in details or trying to start it.

What the hell is going on?

**Comment by bodograumann** [comment]
After starting sidequest once more, it seems now suddenly beaton works again. Can not start beatsaber though.

**Comment by bodograumann** [comment]
Installing beaton again in sidequest. This looks very different from the time before...

No custom songs in beaton again. It says I should restore - whatever that means. so lets try that.

Seems to have brought back my custom songs. Syncing… 
Well custom songs work. Scores still gone ofc.
Wait, what about my imagine dragons pack? It says i need to buy the songs. But I bought it with the iniital game purchase. Not sure if this was already like that after the vanilla update.

So have to go back to the vanilla state to check. Choosing beaton icon and restore beatsaber...

Ah, it uninstalls the patched version, but is not able to reinstall the backup because of
> INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1565799334.tmp/base.apk: AndroidManifest.xml

But at least beatsaber is cleanly uninstalled now.
Reinstalling vanilla...

**Comment by bodograumann** [comment]
Trying to install vanilla I get “this feature isnt working right now. check your internet connection”.
Rebooting the quest… (that helped before, but why is it necessary???)
Yes, now its downloading and installing vanilla beatsaber, again.

Sooo, in vanilla beatsaber, the imagine dragons pack is installed fine. Downloaded all the songs now. Lets patch again.

Side note: when opening the beaton install dialog in sidequest and pulling the slider from off to on, the status of beatsaber and beaton on the left is only updated to the correct value after a certain delay. Until the data has been read completely, any **action buttons on the right should be disabled!**

Back to topic: Patching worked. All original songs and imagine dragons are still accesible. Only the latter ones have to be downloaded again.

But my custom songs are not in beaton and I did not get the restore dialog this time.
Ooh, seems the quest lost the wifi connection again.
Seems that is also causing many of the problems with beaton.
Not sure what is causing the wifi problems. (Seems to happen after patching with beaton?!?)
If I understand it correctly now, beaton can not work solely over usb-c connection, but needs wifi!?
My **suggestion** would then be: Still show the “BEAT ON” link on the top right, but when clicking on it, show a notification that there is a problem with the wifi connection. Maybe also include some suggestions for fixing it.

I guess I do remember that even when standing right next to the wifi router there have been times when the quest lost connection mid-game. Now it came back by itself...

**Comment by bodograumann** [comment]
Still missing my custom songs, trying “Reload Songs Folder“.
Kinda found my custom songs, but not in the playlists i put them in.
Maybe “Quick Fix” will help...  No. Now the custom songs are gone again.
*Shouldnt they be in sidequest?*
Doing “Reload Songs Folder“ again. Oh no, this is taking forever... Ctrl+C
Uhm, songs are there without playlists nor names.

Also, most importantly in “My Playlists” there is OST1-3 and Extras, but no imagine dragons. I will not try sync again.

Trying “Resetting changes“. Also taking for forever… Ctrl+C

Ok I'm fed up for now, maybe trying again at some other time.

**Comment by srvrguy** [comment]
For general support, it's recommended to use our Discord group. You can access it at https://discord.me/sidequestvr.

As for your issues:
- If you haven't done updates in a while, it will be more difficult to update as things move very fast. Especially if you've been using the ancient patch-on-computer method. The transition tools to BeatOn no longer exist in SideQuest.
- When using the old patch method or BeatOn, upgrades to Beat Saber will not work automatically because they both modify the program, breaking the update validation. You need to uninstall Beat Saber in order to get the new version from the Oculus store.
- If you make sure to open Beat On before removing Beat Saber, the newer versions of Beat On attempt to make a copy of your saved data such as scores. Alternately, there's a nice process on how to manually backup this stuff over on [this wiki page](https://github.com/the-expanse/SideQuest/wiki/Beatsaber-update-%23.%23.%23-is-out,-can-i-install-it%3F)
- The "same network" error can be caused by a lot of issues such as using a proxy server or VPN on the computer you're running SideQuest. It's showing because the Quest headset isn't responding to pings. If Beat On is installed, you can always open it directly on your headset.
- As part of the Beat On installation, it needs to uninstall Beat Saber so it can install a slightly modified version that allows customization. This is normal.
- Sometimes SideQuest can't detect BeatOn on the headset. Clicking on the top bar button and toggling the slider to On usually triggers SideQuest to detect Beat On (and gets it running on the headset so you can use it).

**Comment by bodograumann** [comment]
Thanks for the discord link. I guess the major thing that confused me, was the loss of the network connection, which was not clearly indicated in the SideQuest UI. Depending on how far I got with starting BeatOn, it broke the UI at different places.

After using the “Reload Songs Folder” two more times and then syncing to the Quest, it seems the custom songs are back and this time the Imagine Dragons Pack is also still working.

So I honestly can not say whether the issues where only caused by bad wifi connectivity, or if there are some bugs. Especially restoring Beat Saber to the original version might be broken, but I’m not trying this out, now that everything works. Maybe on the next update I will have a look.
