### ISSUE TITLE
How can I add scrcpy.jar to the adb folder?

### ISSUE THREAD

**Issue by SpookyBear0** [the-expanse/SideQuest#299]
Just some genuine help, as I am trying to contribute to this project, I want to add a casting option. Thanks

**Comment by shaneharris** [comment]
Hi There! 

scrcpy is a common request soo we have a plan to attempt to integrate it. It heavily depends on wireless ADB ( pretty useless without it ) so we are rolling out experimental beta wifi ADB support in the coming days. Once that has settled down well do another version that simplifies it further. 

The issue with scrcpy is that it adds a java dependency on all platforms. The ideal way to integrate scrcpy would be to download the binary when the user optionally enables it, it should also check for a compatible version of java installed - prompting the user to install java if they do not. 

We are planning on introducing this but we want to make sure we do it properly and don't get inundated with support requests because the setup is temperamental. If you wouldn't mind holding off for a short while so we can roll this out and minimize the crazyness in our support channels?

**Comment by shaneharris** [comment]
Hi there, just an update on this. We rolled out the wifi option yesterday and things have gone really well so far it seems. We will be eager to integrate this as soon as possible.

**Comment by shaneharris** [comment]
this is coming in the next version thankfully! in a few days!
