### ISSUE TITLE
please give ability to not show paid apps

### ISSUE THREAD

**Issue by scott-adamson1975** [the-expanse/SideQuest#311]
please provide the ability to include or filter out paid apps from the lists, most of the paid apps are ones that are no of sufficient quality to even be considered for the oculus store or are buggy and will never be completed.

side quest should not be a store for people to sell poor sdk demos compiled to make a fast buck.

a demo/cut down/beta version in the filtered list should be permissible with a link to it's paid version

many people do not want to end up seeing pages and pages of 2 euro experiences that arnt worth the bytes they are wasting or the time they took to create.

please don't let this become the quest version of the android play store

**Comment by shaneharris** [comment]
Hi There! In order to continue to receive content developers need to be able to monetize their apps - this is a priority of the SideQuest team. We are sorry that some of these are not up to spec but its important to understand that the content wont keep coming for free. There is no such thing as a fast buck here, just some people working hard to try to make something people will enjoy. That being said I'm pretty sure the the majority on SideQuest are free apps.
