### ISSUE TITLE
SideQuest disconnects while installing apps on Linux

### ISSUE THREAD

**Issue by Elettrotecnica** [the-expanse/SideQuest#317]
I experience frequent random disconnects while installing applications on my Linux machine. The device immediately reconnects, but the task fails. I can eventually manage to install what I want after several attempts. 

My system is running Debian buster on kernel 4.19.0-6-amd64. SideQuest version is 0.7.4. I can provide further information if needed.

Can anybody else confirm this issue?

**Comment by shaneharris** [comment]
Hi there, this is usually caused by a faulty USB cable, or a bad usb port but those are usually users on windows so there could be other issues there. A good test here would be to see if ADB also disconnects when installing large files on the command line - if it does then its something low level ( usb driver issue ) or a hardware issue. If it doesn't then it could be an issue with SideQuest.

**Comment by shaneharris** [comment]
Just a follow up here, this is sometimes caused by using a usb 3 port, try swapping to usb 2
