### ISSUE TITLE
disconnected.. can not connect

### ISSUE THREAD

**Issue by ghost** [the-expanse/SideQuest#320]
I have tried everything I can to get sidequest to connect to quest.
cables , sidequest reinstalls, oculus drivers, adb paths, every usb port on my pc, using a laptop, restarts, reboots dev mode on off on off restarts more cables, antivirus disable..  etc etc etc..
skybox and pc can see it and when dev mode but not when its on/
 just can't get it to see quest. any suggestions

**Comment by ChibiBlaziken** [comment]
https://github.com/the-expanse/SideQuest/wiki/I-am-having-issues-Connecting-,-what-do-i-do%3F

The most comprehensive list of issues and their Solutions are located
within this link, I do hope it assists  but otherwise you can if you're
aware of how to attempt to make an alternative user on your computer and
log into that if you're aware of how to attempt to make an alternative user
on your computer and log into that in the one before. Trying to see if it
is a specific user setting causing issue

**Comment by eddies36** [comment]
Solved.. ended up being the adb paths were wrong and I was missing a driver
