### ISSUE TITLE
I cannot install new versions of SideQuest

### ISSUE THREAD

**Issue by Righ7y** [the-expanse/SideQuest#322]
Anytime I download an installer and use it, it tells me that the installation was aborted and not successful. I'm stuck on an older version because of this.
![image](https://user-images.githubusercontent.com/57548752/68519684-8a61c280-0260-11ea-98a0-48b76ae3ca62.png)

**Comment by shaneharris** [comment]
Hi there! This problem is caused by the portable edition of sidequest which is now deprecated. It tried to auto update and as such it breaks the installer/upater. If you delete these folders then try the install again it should go through:

`C:\Users\USERNAME\AppData\Local\sidequest-updater`

`C:\Users\USERNAME\AppData\Local\Programs\SideQuest`

`C:\Users\USERNAME\AppData\Roaming\SideQuest`
