### ISSUE TITLE
Drag-drop apk files: often there is no "Drop files here!" message

### ISSUE THREAD

**Issue by arigo** [the-expanse/SideQuest#342]
Drag-and-dropping apk files from the Windows explorer to the SideQuest window: this is often painful in SideQuest v0.8.4.  Most of the times the message "Drop files here!" does not appear and dropping the file does nothing.  I found out that if you aim precisely for the "connection status" green/red dot in the top-left corner, then it works as expected.  It also works if you aim for the status bar, provided there is one visible now.

What I expect is that it should work if you drop the file anywhere in the SideQuest window.

**Comment by shaneharris** [comment]
Hi there! Thanks for your comment and I appreciate your frustration. The issue is that the webpages will also want to be able to consume those drag and drop events and some users are using websites ( bsaber.com, the BMBF page ) that require drag and drop for some reason or another. This makes it difficult to be able to negotiate this and we have even considered removing drag and drop altogether but we worry that the user base might react negatively to that. We have considered adding drag and drop to the sidequest website and this may work so there is some hope. 

Thanks for your suggestion again ill keep this open so I can investigate this more in terms of a workaround.

**Comment by sidequestlegend** [comment]
I have investigated the potential of this and unfortunately there is no clean way to implement this. We plan to accomodate this int he docs by explaining that you should drag & drop files onto the tasks screen in sidequest which trigggers the drop from any position on the app.
