### ISSUE TITLE
Feature Request: Android SideQuest marketplace app that runs natively on the Quest?

### ISSUE THREAD

**Issue by BrainSlugs83** [the-expanse/SideQuest#409]
I think I asked for this awhile back on Reddit, and the answer was something like "we're working on a new web based UI now, and this will be coming soon." -- But I haven't seen any mention of it, so I wanted to log a request here to get it in the backlog if it's not already.  (If it is already, apologies, feel free to close as a duplicate.)

But the request is to have an Android version of SideQuest (it's fine if it needs to be installed by the desktop app or whatever... but ideally, I don't want to have to plug it into the PC every time)...

The app could be a SideQuest "lite", which just gives access to install and update side loaded apps, like a grid based market place, maybe a search feature, and a "check for updates button" or something?

I'm not an Android expert, but I believe that over ADB you should be able to grant an app permissions to install other apks (along with any other permissions it may need).

It would be great to just sit on my couch, throw on my headset, and browse what's new and start trying things out as I download them, without having to go through a big setup ordeal every time.

**Comment by NotWoods** [comment]
Perhaps an on-device version could just be a wrapper around a web browser that lets you install APKs? Since you can install APK files using file explorer apps it may be possible to integrate into a single browser+view downloads app. That way, there doesn't need to be a custom mobile UI.

**Comment by shaneharris** [comment]
I get asked this a lot, the answer is complicated but always the same. 

I'm afraid this is not quite as easy as it sounds, we tested this a lot at the start and originally intended to run sidequest inside the headset but here is the full run down. So its not possible to install APK files silently, not without a signing cert from the manufacturer and also some other hacky methods ( sharing uuid's with the system app ) and I actually believe oculus has [disabled features](https://www.reddit.com/r/sidequest/comments/f7dc95/devs_does_the_appupdater_in_the_applauncher/) of the package manager that could make this possible. 

The file explorer can install APK files for sure, it does so with the native android install wizard screen. The problem here is that screen has not been built for VR and often results in weird behaviour like it can appear in non-stereo mode or take the screen out of side-by-side mode entirely - which is extremely uncomfortable for anyone in VR. If you're lucky and that doesn't happen the best case scenario is that it will install OK and on the last screen of the installer it will present you with the option to open the app which puts you into a black screen that you cannot get out of without rebooting the headset or killing the process externally ( from PC ). Because of all of these issues it meant that supporting that workflow would result in person after person asking why it was broken or what was wrong and with no control over that workflow we would not be able to do anything about it - this is support that we simply can not offer due to our limited resources. In the end the simplest experience for the end user was to take the desktop app route as we were aiming sidequest to be as user friendly as possible. This reduced the complexity and steps required to get up and running in an already convoluted workflow - we even built it without enforcing user signups as this would have added 2-3 more steps for the users to be able to install apps.  

Then there is the issue of how do we get the APK for this app onto the headset in the first place? This means that even in a limited fashion we would have to maintain both a desktop ADB installer as-well as the android one, given that we need an ADB installer to get the android one installed in the first place - and I could imagine we would have a lot of requests at that point for being able to browse and install apps from PC - this would effectively double our maintenance and support requirement with two solutions essentially achieving the same thing. 

Another benefit of the current workflow is that sidequest has been isolated from the headset, and actually works with any android based device without requiring any manufacturer software or SDKs or even accepting third party licenses. This has protected us from legal issues or preventative posturing by the manufacturer - we are protected behind the shield of ADB. This has meant that rather than focus our development time on workarounds to the inevitable cat and mouse situation that an on-device solution would result in, we have been able to focus our limited resources on improving the application. 

All that being said, we have a workaround that provides most of this functionality called remote installs. Essentially the sidequest desktop app can be remotely controlled from any browser as long as you are logged into both the desktop app and the controlling browser on the same sidequest account ( this even works over the internet ). This still requires that the headset and desktop app are connected, but this can be done over wifi. Wireless ADB requires that you reconnect the headset after every reboot as the wireless access is disabled when the headset restarts. sidequest 10 ( releasing soon ) will be able to re-establish the wifi connection as long as the headset has not been rebooted - it currently needs to be connected every time to restart sidequest. This means you can get a lot of the same value, without all the added complexity and risk. The remote install feature has been live since sidequest 8 released at Christmas time last year. 

I hope this provides some background on the nature of this issue and some useful info on how you can achieve this today.
