### ISSUE TITLE
Everything is gone

### ISSUE THREAD

**Issue by SheeperBeeper** [the-expanse/SideQuest#487]
I just installed SideQuest for my Oculus Quest and everything has disappeared. I followed the instructions and when I put on my headset everything was gone except my little Oculus bar that allowed me to go to my library, tv, etc. I tried to do something and pressed on my library and stuff but nothing appeared. I pressed tv and when I did it told me that I should create an avatar. I found it weird so I restarted my Quest. When I did everything including my Oculus bar was gone. I wasn't able to do anything.

**Comment by FluxXxBoy** [comment]
It's just because of version 16 of Oculus Quest firmware, it will be solved in the next days.
On some sites, you can find a spoofed (as the app "within") version of sidequest launcher that work.

**Comment by SheeperBeeper** [comment]
But what do I do right now. I can't play anything so is the only option to factory reset?

**Comment by RedBrumbler** [comment]
that would not solve the issue, the issue is that some apps did not put a specific line in their manifest and that made them not show up on your quest, the way to fix this is for the creators of those apps to update their manifests so the app can show up again

at least that is my understanding of it
