### ISSUE TITLE
SideQuest not working properly after compilation

### ISSUE THREAD

**Issue by ChillSheep** [the-expanse/SideQuest#507]
Hi, I want to compile  sidequest myself but after unpacking everything and installing the packages, 
after running "yarn dist", the sidequest exe will not load url's.

**Comment by rgstoian** [comment]
Can confirm, building the latest sources results in a non-functional version of SideQuest labeled 0.10.3.

The source code doesn't seem to have been updated (except for package dependencies) since March 17th.

Platform: Windows 10 Pro x64
Environment: node.js 12.16.3, yarn 1.22.4

URLs don't load:
![SideQuest_Y3qgwsO05O](https://user-images.githubusercontent.com/49798196/80914067-ec077300-8d51-11ea-8434-cbcdffe6ef01.png)

JS code doesn't execute at all (my Quest is actually connected in the screenshot):
![SideQuest_F1khi5TQVL](https://user-images.githubusercontent.com/49798196/80914203-b57e2800-8d52-11ea-95f7-0227e5cbefb0.png)

Pre-compiled binaries are functional, as well as v0.10.2 built from sources.
