### ISSUE TITLE
Restore urls of apps to web site view

### ISSUE THREAD

**Issue by korenmic** [the-expanse/SideQuest#527]
To allow using an alternative downloader other than sidequest for downloading the apps.

Reason this is currently crucial is
that if I pick 20 new apps to install
"launch and forget"

and for example my pc restarts or sidequest crashes before the process is complete
the entire list is lost, while when using any other alternative modern downloader, the download list status and progress db sustains restarts.
Also the speed is increadibly slow, and without urls in the web site, it proves difficult extracting the links and passing them to a more reliable downloader software.
https://github.com/the-expanse/SideQuest/issues/526

**Comment by sidequestlegend** [comment]
I'm afraid this wont be possible due to some recent changes in sidequest. We have had an issue with people [taking free games from sidequest and attempting to sell them](https://t.me/s/questgameclub)

For this reason we have decided to take the download urls off the public page listings and Im not sure if we can bring them back. ill comment over on #526
