### ISSUE TITLE
Confused - UI in Sidequest Appears Different from Tutorials, Features Missing?

### ISSUE THREAD

**Issue by Miduzi** [the-expanse/SideQuest#565]
Hello - trying to get beastsaber up and running, however the UI on the version of sidequest I've installed is totally different from the UI in the tutorials I'm following and it appears that quite a few features are missing.

Here is what I'm seeing:

![What I See](https://user-images.githubusercontent.com/66493938/83918864-6733be80-a72e-11ea-8579-f5374836e2f8.PNG)

This is the view that appears in tutorials:

![Tutorial View](https://user-images.githubusercontent.com/66493938/83918904-79156180-a72e-11ea-81fe-2ffd4db9710a.PNG)

I'm not the most technically inclined person, where did I go wrong?

**Comment by ChibiBlaziken** [comment]
Most videos on youtube are far outdated, for help installing SideQuest see the Get SideQuest 
pages guide at SideQuestVR.com or head to https://github.com/the-expanse/SideQuest/wiki/SideQuest-Setup-&-How-To-install
A good rule of thumb when dealing with sideloading is not to trust youtube as things change and evolve fast, if trying to install pirated content like beatsaber that was not paid for be aware it will not work, Otherwise as it states you are not connected still see the connection support page in the previously linked Github how to for help with connection issues and it should get you running again.

**Comment by sidequestlegend** [comment]
As Chibi says above a lot has changed im afraid. this is the best video to use now - https://sdq.st/video

**Comment by Miduzi** [comment]
Thank you!
