### ISSUE TITLE
Tools Feature Request

### ISSUE THREAD

**Issue by Ionwerks** [the-expanse/SideQuest#593]
Wanted to suggest a new feature and a change for the _Tools_ page;

1. Beat Saber data backup. Would be really neat to have a one-click local data backup option for BS. Ideally you'd be prompted for a zip file name, preset to the path last used and a date-based default file name (BSData-YYYY-MM-DD.zip).

2. I think it'd be useful if each tweaking option (texture size, FFR etc.) had some text or button highlight to indicate what the default value actually is (as far as is known, and with a "current as at DD/MM/YY" disclaimer if there's any doubt). Any time I'm in there and think I should really play with these I immediately then think 'maybe later' because to make a useful comparison I'd first have to research the default values so I understand whether I've just set something higher/lower and by how much.

Thanks for your valuable work and for considering the above.

**Comment by sidequestlegend** [comment]
Im unwilling to make an individual backup system for just one app as it would lightly prompt the same for several other apps. We have done specific features for certain apps in the past and still do in some cases for legacy reasons but we have moved towards more generic features that accomodate most apps as things often change with individual aps and it would require too much maintenance to stay on top of the nuances for all apps that way. 

As regards the default, I can display what the default buttons are doing in the app, but again its a lot of work to try to test out those features on each new firmware and trying to estimate what the default value is in some cases. The problem here is that we are working against mostly non-public APIs and i'm inclined to retire these features rather than put a lot of energy into checking if/how they work on each new firmware update.
