### ISSUE TITLE
Emergency Fix Crashes on Launch on Mac (maybe other systems too)

### ISSUE THREAD

**Issue by ryanlauderbach** [the-expanse/SideQuest#68]

**Comment by jaredgei** [comment]
yep same here

**Comment by SteveW25561** [comment]
Here's the error I get on launch:

Process:               SideQuest [4527]
Path:                  /Applications/SideQuest.app/Contents/MacOS/SideQuest
Identifier:            com.electron.sidequest
Version:               0.2.0 (0.2.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SideQuest [4527]
User ID:               502

Date/Time:             2019-06-04 19:14:49.309 -0700
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Anonymous UUID:        D7A1CB72-888D-4574-9B41-136AA0471FBA


Time Awake Since Boot: 230000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libffmpeg.dylib
  Referenced from: /Applications/SideQuest.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
  Reason: image not found

**Comment by justinb26** [comment]
For a quick fix, copy the Electron.framework from SideQuest 0.2.0 (SideQuest.app -> Show Package Contents -> Contents/Frameworks/Electron.Framework) to the equivalent location in the SideQuest 0.2.1a app

**Comment by belongstorachel** [comment]
Something must have gone wrong in the build which is weird because when I build it from source, it doesn't crash when it's loaded. If you happen to want to build it from source, here's what I did: 

1. Install [NodeJS](https://nodejs.org/en/)
2. Download the [source](https://github.com/the-expanse/SideQuest/archive/0.2.1-alpha.1.tar.gz) and extract it
3. Open the terminal and change to the folder that was created (`SideQuest-0.2.1-alpha.1`)
4. Run `npm install`
5. Run `npm install electron-packager -g`
6. copy and paste this into the terminal `mkdir -p build && cd build && electron-packager --platform=darwin --arch=x64 ../ "SideQuest" --overwrite --ignore="/mobile-launcher|/desktop-app/platform-tools|/build"`

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S
