### ISSUE TITLE
Toggle permissions of installed applications

### ISSUE THREAD

**Issue by SCheeseman** [the-expanse/SideQuest#85]
Currently the Pavlov alpha requires adb to permit the application access to the Microphone:
`adb shell pm grant com.davevillz.pavlov android.permission.RECORD_AUDIO`
It'd be useful to have this functionality within SideQuest (along with other permissions).

**Comment by shaneharris** [comment]
Great suggestion! this feature is already underway and coming very soon!

**Comment by Bluscream** [comment]
My idea is to have a new button called "Permissions" in the options for each app

![image](https://user-images.githubusercontent.com/3318223/72246497-1f7f8f80-35f3-11ea-963c-a53dbbd8f0d5.png)

Which opens a new popup that lists all permissions that can be changed through ADB and allows granting/denying them through a simple checkbox next to each permission,

![image](https://user-images.githubusercontent.com/3318223/72246993-41c5dd00-35f4-11ea-9ab3-fbb64ebbf269.png)

**Comment by Bluscream** [comment]
Remember to remove the button for Pavlov's mic permission from the settings. (You might wanna integrate that + the question for the name into the installation process for Pavlov itself)

**Comment by shaneharris** [comment]
OK this has been somewhat implemented and will be out in the next release coming soon. Because there are a lot of perms that cannot be set from the UI I am working from a hardcoded list of perms and only if they exist on the device. Those only include READ_/WRITE_EXTERNAL_STORAGE and RECORD_AUDIO. I will add more if they are needed but this probably covers 95% of the use case and useful for most SideQuest users.
